### ISSUE TITLE
 rootless不支持

### ISSUE THREAD

**Issue by ghost** [suifengFly1/MonkeyDev#4]
111

**Comment by LongMeters** [comment]
未有支持计划

**Comment by ghost** [comment]
> 未有支持计划

方便教一下怎么在monkeydev中修改配置，以让它支持rootless。我不太想通过theos命令去构建...

**Comment by LongMeters** [comment]
<img width="282" alt="image" src="https://github.com/LongMeters/MonkeyDev/assets/150657615/4b61ff70-6314-458b-a5aa-8becc424307c">
修改此目录结构
<img width="674" alt="image" src="https://github.com/LongMeters/MonkeyDev/assets/150657615/5be8c448-629e-4136-9119-ece711d28699">
修改此配置

**Comment by ghost** [comment]
> <img alt="image" width="282" src="https://private-user-images.githubusercontent.com/150657615/307489059-4b61ff70-6314-458b-a5aa-8becc424307c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NDI3NDUsIm5iZiI6MTcwODc0MjQ0NSwicGF0aCI6Ii8xNTA2NTc2MTUvMzA3NDg5MDU5LTRiNjFmZjcwLTYzMTQtNDU4Yi1hNWFhLThiZWNjNDI0MzA3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQwMjQwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTM4ZDk2NmMzZjhkYzI4ZjRjNzk0MDE0MWNiZGQ5ZGE3MmZiNDlmOTE5M2RlZDA0MzE5MDBkNDRlYWMwOTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2LqDaHSFFvxLjFObklvSyKJavMI04mFMcAQh1gK-8Ho"> 修改此目录结构 <img alt="image" width="674" src="https://private-user-images.githubusercontent.com/150657615/307489093-5be8c448-629e-4136-9119-ece711d28699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NDI3NDUsIm5iZiI6MTcwODc0MjQ0NSwicGF0aCI6Ii8xNTA2NTc2MTUvMzA3NDg5MDkzLTViZThjNDQ4LTYyOWUtNDEzNi05MTE5LWVjZTcxMWQyODY5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQwMjQwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjEwNzJkMjhlNmRhODQwOWU1ZGE1NTkyOTczZmEyMzU3YmU3NDllZjJkN2VlMTFkYWUxNzE5OWE0YTQ4N2Y3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OlbeJPmvoFGfRfPmVagKIpKIJxXY6f1SBtzbPjn3crw"> 修改此配置

卧槽！！！醍醐灌顶啊！！我竟然忽视了有根和无根区别。。。大佬我给你买杯可乐吧！

**Comment by LongMeters** [comment]
> > <img alt="image" width="282" src="https://private-user-images.githubusercontent.com/150657615/307489059-4b61ff70-6314-458b-a5aa-8becc424307c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NDI3NDUsIm5iZiI6MTcwODc0MjQ0NSwicGF0aCI6Ii8xNTA2NTc2MTUvMzA3NDg5MDU5LTRiNjFmZjcwLTYzMTQtNDU4Yi1hNWFhLThiZWNjNDI0MzA3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQwMjQwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YTM4ZDk2NmMzZjhkYzI4ZjRjNzk0MDE0MWNiZGQ5ZGE3MmZiNDlmOTE5M2RlZDA0MzE5MDBkNDRlYWMwOTg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2LqDaHSFFvxLjFObklvSyKJavMI04mFMcAQh1gK-8Ho"> 修改此目录结构 <img alt="image" width="674" src="https://private-user-images.githubusercontent.com/150657615/307489093-5be8c448-629e-4136-9119-ece711d28699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NDI3NDUsIm5iZiI6MTcwODc0MjQ0NSwicGF0aCI6Ii8xNTA2NTc2MTUvMzA3NDg5MDkzLTViZThjNDQ4LTYyOWUtNDEzNi05MTE5LWVjZTcxMWQyODY5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQwMjQwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjEwNzJkMjhlNmRhODQwOWU1ZGE1NTkyOTczZmEyMzU3YmU3NDllZjJkN2VlMTFkYWUxNzE5OWE0YTQ4N2Y3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OlbeJPmvoFGfRfPmVagKIpKIJxXY6f1SBtzbPjn3crw"> 修改此配置
> 
> 卧槽！！！醍醐灌顶啊！！我竟然忽视了有根和无根区别。。。大佬我给你买杯可乐吧！

感谢，一起进步即可。
